# Generated by Django 3.1.1 on 2020-09-14 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0003_auto_20200912_2204"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="address_line_1",
            field=models.CharField(
                blank=True, help_text="Address Line 1", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="address_line_2",
            field=models.CharField(
                blank=True, help_text="Address Line 2", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="postal_code",
            field=models.CharField(
                blank=True, help_text="Postal Code", max_length=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="state",
            field=models.CharField(
                blank=True, help_text="Province / State", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="q1",
            field=models.TextField(
                help_text="Why do you want to participate in NewHacks?", max_length=1000
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="q2",
            field=models.TextField(
                help_text="Tell us about your experience with software or other topics relevant to NewHacks!",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="q3",
            field=models.TextField(
                help_text="How did you hear about NewHacks?", max_length=100
            ),
        ),
    ]
