# Generated by Django 3.1.1 on 2020-10-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0006_auto_20200917_1953"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="rsvp",
            field=models.BooleanField(null=True),
        ),
    ]
