# Generated by Django 3.2.5 on 2021-08-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0008_auto_20210818_1720"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="how_many_hackathons",
            field=models.TextField(
                choices=[
                    (None, ""),
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5 or more", "5 or more"),
                ],
                help_text="How many hackathons have you been to?",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="what_hackathon_experience",
            field=models.TextField(
                help_text="If you’ve been to a hackathon, briefly tell us your experience. If not, describe what you expect to see and experience.",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="what_technical_experience",
            field=models.TextField(
                help_text="What is your technical experience with software and hardware?",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="why_participate",
            field=models.TextField(
                help_text="Why do you want to participate in NewHacks?", max_length=1000
            ),
        ),
    ]
