# Generated by Django 3.1.12 on 2021-09-02 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0009_auto_20210819_1814"),
    ]

    operations = [
        migrations.RenameField(
            model_name="application", old_name="data_agree", new_name="resume_sharing",
        ),
    ]
